server:
  port: 8080
  servlet:
    session: 
      timeout: 1800
    context-path: /nimbus-samples-repws
    
spring:
  application:
    name: nimbus-samples-repws
    
  h2:
    console:
      enabled: true
      path: /console/
    
  data:
    mongodb:
      host: localhost
      database: nimbus-samples-web
      port: 27017
      
  activiti:
    processDefinitionLocationPrefix:  classpath*:process-defs/**.xml
    
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
  sqldatasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
        
nimbus:
  domain:
    model:
      basePackages: 
        - com.antheminc.oss.nimbus.entity
        - com.antheminc.oss.nimbus.samples.repws.core
        - com.antheminc.oss.nimbus.samples.repws.view

  ext:
    repository:
      targetUrl: 
        book: http://localhost:8080/nimbus-samples-repws/api/books
  
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%X{SESSIONID:- }] --- [%t] %-40.40logger{39} : %replace(%replace(%m){'\n', ''}){'\r', ''} %n${LOG_EXCEPTION_CONVERSION_WORD: %wEx}"  
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%X{SESSIONID:- }] --- [%t] %-40.40logger{39} : %replace(%replace(%m){'\n', ''}){'\r', ''} %n${LOG_EXCEPTION_CONVERSION_WORD: %wEx}"
